package com.hbyd.parks.domain.managesys;

// Generated 2014-6-18 13:23:23 by Hibernate Tools 3.4.0.CR1

import com.hbyd.parks.common.base.RecoverableEntity;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * Department generated by hbm2java
 */

@Entity
@Table(name = "base_department")
public class Department extends RecoverableEntity{
	private String deptCode;
	private String deptName;
	private String abbrName;
	private String deptDesc;

    @ManyToOne
    @JoinColumn(name = "parentFK", referencedColumnName = "id")
	private Department parent;

	/**
	 * 该字段仅在获取部门数据时有效，保存时无效
	 */
    @OneToMany(mappedBy = "parent")
	private Set<Department> childDepts = new HashSet<Department>(0);

	public Department() {
	}

	public Department getParent() {
		return parent;
	}

	public void setParent(Department parent) {
		this.parent = parent;
	}

	public String getDeptCode() {
		return deptCode;
	}

	public void setDeptCode(String deptCode) {
		this.deptCode = deptCode;
	}

	public String getDeptName() {
		return deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	public String getAbbrName() {
		return abbrName;
	}

	public void setAbbrName(String abbrName) {
		this.abbrName = abbrName;
	}

	public String getDeptDesc() {
		return deptDesc;
	}

	public void setDeptDesc(String deptDesc) {
		this.deptDesc = deptDesc;
	}

	public Set<Department> getChildDepts() {
		return childDepts;
	}

	public void setChildDepts(Set<Department> childDepts) {
		this.childDepts = childDepts;
	}

}
