package com.hbyd.parks.domain.managesys;

// Generated 2014-6-18 13:23:23 by Hibernate Tools 3.4.0.CR1

import com.hbyd.parks.common.base.BaseEntity;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "base_user")
public class User extends BaseEntity {

    /**
     * 登录名称
     */
    private String userName;
    /**
     * 登录密码
     */
    private String password;
    /**
     * 登录名称的昵称
     */
    private String nickname;

    /**
     * 性别
     */
    private String gender;

    /**
     * 实名
     */
    private String realName;

    /**
     * 所属部门
     */
    @ManyToOne
    @JoinColumn(name = "departmentFK", referencedColumnName = "id")
    private Department department;

    /**
     * 拥有的角色
     */
    @ManyToMany
    @JoinTable(name = "base_user_role", joinColumns = {
            @JoinColumn(name = "userFK", referencedColumnName = "id")
    }, inverseJoinColumns = {
            @JoinColumn(name = "roleFK", referencedColumnName = "id")
    })
    private Set<Role> roles = new HashSet<Role>();

    public String getGender() {
        return gender;
    }


    public void setGender(String gender) {
        this.gender = gender;
    }


    public String getRealName() {
        return realName;
    }


    public void setRealName(String realName) {
        this.realName = realName;
    }


    public User() {
    }

    public Department getDepartment() {
        return department;
    }

    public void setDepartment(Department department) {
        this.department = department;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public Set<Role> getRoles() {
        return roles;
    }

    public void setRoles(Set<Role> roles) {
        this.roles = roles;
    }


}
