package com.hbyd.parks.dto.managesys;

// Generated 2014-6-26 13:14:36 by Hibernate Tools 3.4.0.CR1

import com.hbyd.parks.common.base.BaseDTO;

import java.util.HashSet;
import java.util.Set;

/**
 * Department generated by hbm2java
 */
public class DepartmentDTO extends BaseDTO {

	private String abbrName;
	private String deptCode;
	private String deptDesc;
	private String deptName;

	private Set<DepartmentDTO> childDepts = new HashSet<>();
	private String parentId;

	public String getParentId() {
		return parentId;
	}

	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	public DepartmentDTO() {
	}

    public Set<DepartmentDTO> getChildDepts() {
        return childDepts;
    }

    public void setChildDepts(Set<DepartmentDTO> childDepts) {
        this.childDepts = childDepts;
    }

	public String getAbbrName() {
		return abbrName;
	}

	public void setAbbrName(String abbrName) {
		this.abbrName = abbrName;
	}

	public String getDeptCode() {
		return deptCode;
	}

	public void setDeptCode(String deptCode) {
		this.deptCode = deptCode;
	}

	public String getDeptDesc() {
		return deptDesc;
	}

	public void setDeptDesc(String deptDesc) {
		this.deptDesc = deptDesc;
	}

	public String getDeptName() {
		return deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}
}
