package com.hbyd.parks.dto.managesys;

// Generated 2014-6-26 13:14:36 by Hibernate Tools 3.4.0.CR1

import com.hbyd.parks.common.base.BaseDTO;

import java.util.Set;

/**
 * SysApplication generated by hbm2java
 */
public class ResAppDTO extends BaseDTO implements Comparable<ResAppDTO>{
    /**
     * 是否可见，有些功能只有开发和部署人员才能看到，即使是客户的管理员也不能看到
     */
    private Boolean isVisible;
	private String appName;
	private String appDesc;
	private Integer appOrder;
	private String appPageUrl;

    /**
     * 保存、更新子系统时，需要重新关联其下的菜单，只需要菜单 ID 列表即可，为了方便映射，这里使用 MenuDTO
     */
    private Set<ResMenuDTO> resMenus;

	public ResAppDTO() {
	}

    public Boolean getIsVisible() {
        return isVisible;
    }

    public void setIsVisible(Boolean isVisible) {
        this.isVisible = isVisible;
    }

    public Set<ResMenuDTO> getResMenus() {
        return resMenus;
    }

    public void setResMenus(Set<ResMenuDTO> resMenus) {
        this.resMenus = resMenus;
    }

	public String getAppName() {
		return appName;
	}

	public void setAppName(String appName) {
		this.appName = appName;
	}

	public String getAppDesc() {
		return appDesc;
	}

	public void setAppDesc(String appDesc) {
		this.appDesc = appDesc;
	}

	public Integer getAppOrder() {
		return appOrder;
	}

	public void setAppOrder(Integer appOrder) {
		this.appOrder = appOrder;
	}

	public String getAppPageUrl() {
		return appPageUrl;
	}

	public void setAppPageUrl(String appPageUrl) {
		this.appPageUrl = appPageUrl;
	}


    @Override
    public int compareTo(ResAppDTO s) {
        return Integer.compare(this.appOrder, s.appOrder);
    }
}
