package com.hbyd.parks.dto.managesys;

// Generated 2014-6-26 13:14:36 by Hibernate Tools 3.4.0.CR1

import com.hbyd.parks.common.base.BaseDTO;

import java.util.Set;

/**
 * SysMenu generated by hbm2java
 */
public class ResMenuDTO extends BaseDTO implements Comparable<ResMenuDTO>{

    /**
     * 是否可见，有些功能只有开发和部署人员才能看到，即使是客户的管理员也不能看到
     */
    private Boolean isVisible;
	private Integer menuOrder;
	private String menuName;
	private String menuPageUrl;
	private String menuIconUrl;

//  子系统信息
	private String appId;
    private String appName;

//  菜单信息
    private String parentId;
    private String parentName;
    private Set<ResMenuDTO> childMenus;

//  按钮信息：仅用于信息读取
    private Set<ResBtnDTO> resBtns;

	public ResMenuDTO() {
	}

    public Boolean getIsVisible() {
        return isVisible;
    }

    public void setIsVisible(Boolean isVisible) {
        this.isVisible = isVisible;
    }

    public String getParentName() {
        return parentName;
    }

    public void setParentName(String parentName) {
        this.parentName = parentName;
    }

    public String getAppName() {
        return appName;
    }

    public void setAppName(String appName) {
        this.appName = appName;
    }

    public Set<ResMenuDTO> getChildMenus() {
        return childMenus;
    }

    public void setChildMenus(Set<ResMenuDTO> childMenus) {
        this.childMenus = childMenus;
    }

    public Set<ResBtnDTO> getResBtns() {
        return resBtns;
    }

    public void setResBtns(Set<ResBtnDTO> resBtns) {
        this.resBtns = resBtns;
    }

    public String getAppId() {
        return appId;
    }

    public void setAppId(String appId) {
        this.appId = appId;
    }

    public String getParentId() {
        return parentId;
    }

    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

	public Integer getMenuOrder() {
		return menuOrder;
	}

	public void setMenuOrder(Integer menuOrder) {
		this.menuOrder = menuOrder;
	}

	public String getMenuName() {
		return menuName;
	}

	public void setMenuName(String menuName) {
		this.menuName = menuName;
	}

	public String getMenuPageUrl() {
		return menuPageUrl;
	}

	public void setMenuPageUrl(String menuPageUrl) {
		this.menuPageUrl = menuPageUrl;
	}

	public String getMenuIconUrl() {
		return menuIconUrl;
	}

	public void setMenuIconUrl(String menuIconUrl) {
		this.menuIconUrl = menuIconUrl;
	}

    @Override
    public int compareTo(ResMenuDTO o) {
        return Integer.compare(this.getMenuOrder(), o.getMenuOrder());
    }
}
